# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da859c1ac74b02ebd5dd2da9688191cf1eec783d254c0addc5e094890be5752b1f25583cc4d9992890c684dd2f781a4b07e26594133aa50fb019d1d55331a6a5

test:
  secret_key_base: db98e5d8de23ad4b1d76e76d39bfc470ab030720bbe23c26ce5f9bef91db7a05bd8f31a3867ac636230d6e497c11a343d94820a460a9e40da6976ce872fff541

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
